apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: consumer-kong-admin
  namespace: vkpr
  annotations:
    kubernetes.io/ingress.class: kong
username: kong_admin
credentials:
  - kong-admin-basicauth
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: kong-admin-basicauth
  namespace: vkpr
  annotations:
    kubernetes.io/ingress.class: kong
config:
  hide_credentials: true
plugin: basic-auth
---
apiVersion: v1
kind: Secret
metadata:
 name: kong-admin-basicauth
 namespace: vkpr
 labels:
   konghq.com/credential: basic-auth
stringData:
 username: kong_admin
 password: vkpr123